name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# image should be built for arm64

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag needle
    - name: Save the Docker image
      run: docker save needle | gzip > needle.tar.gz
    - name: Install ssh keys
      run: | 
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.RASPBERRY_PI_IP }} > ~/.ssh/known_hosts
    - name: Copy image to pi
      run: scp -i ~/.ssh/id_rsa needle.tar.gz pi@${{ secrets.RASPBERRY_PI_IP }}:~/apps/needle/needle.tar.gz
    - name: Run image
      run: ssh -i ~/.ssh/id_rsa pi@${{ secrets.RASPBERRY_PI_IP }} "docker load < ~/apps/needle/needle.tar.gz && docker run -d -p 8000:8000 needle -v /home/pi/apps/needle/:/usr/src/app/api/out/"